# Generated by Django 3.2.8 on 2024-10-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0150_alter_branch_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='psswd',
            field=models.CharField(blank=True, default='JcjDKpMJJX', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='FcfLoy5nWF', max_length=30),
        ),
    ]
