# Generated by Django 3.2.8 on 2024-10-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0151_auto_20241007_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='ije8Xen83e', max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='psswd',
            field=models.CharField(blank=True, default='fU5wmCgneS', max_length=30, null=True),
        ),
    ]
