# Generated by Django 3.2.8 on 2024-10-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0145_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='CzOjl919HB8hzFbTBM31', max_length=20, unique=True),
        ),
    ]
